# Generated by Django 2.1.1 on 2019-07-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name_plural': 'Contact Form Submissions'},
        ),
    ]
